### ISSUE TITLE
Consider deprecation in favor of `async-dnssd`

### ISSUE THREAD

**Issue by jrmuizel** [sebasgarcep/dnssd-rs#3]
https://github.com/stbuehler/rust-async-dnssd has a nicer api and integrates with tokio

**Comment by sebasgarcep** [comment]
38bdc6c  just did. Sorry for having you lose your time over here. 👍

**Comment by jrmuizel** [comment]
Do you mind yanking the version that's currently on crates.io?

**Comment by sebasgarcep** [comment]
Please open a new issue for that and I'll do it as soon as I'm done with my classes.
